### ISSUE TITLE
Newsfeedfilter - confirmation

### ISSUE THREAD

**Issue by Kraftakt** [whispeer/whispeerSite#1]
1. Saving the newsfeed settings after selection and confirmation.
2. A confirmation button (SAVE) or (OK) for saving newsfeed settings, if you wont use the ENTER key of your keyboard (or for user who dont know how to confirm).

![newsfeed](https://cloud.githubusercontent.com/assets/13139997/8462976/9e4e5dea-2037-11e5-8867-54349510e648.jpg)

**Comment by Nilos** [comment]
I would also add this to the "who is allowed to read this post" input too!
