### ISSUE TITLE
Removing Images During the Creation of a Post

### ISSUE THREAD

**Issue by Soraltan** [whispeer/whispeerSite#13]
Hi,

while creating a new post the images attached to the post are displayed as thumbnails. Each image can be removed by clicking on the cross-icon right of the image. The cross-icon is, however, much closer to the next-right image (see the attached image). This lead me repeatedly to delete the wrong image. I would find it far more intuitive if the cross-icons would be closest to the image they delete, rather than to some other image.

![x_problem](https://cloud.githubusercontent.com/assets/11201355/17554266/65c625c6-5f0a-11e6-8c9a-d480df324751.png)

**Comment by Nilos** [comment]
Can you post the browser and browser version you are using to access whispeer?

**Comment by Soraltan** [comment]
Firefox 48.0

**Comment by Nilos** [comment]
Next release should fix the problem! Thanks for the bugreport!

**Comment by Soraltan** [comment]
Seems to be solved now. Thanks

**Comment by Nilos** [comment]
Yes should be! 👍
