### ISSUE TITLE
deploy new private landing page for valentines day promo

### ISSUE THREAD

**Issue by kelzenberg** [whispeer/whispeerSite#18]
change the already done landing page so that the valentines day promo disappears

**Comment by xyng** [comment]
Ich glaube das haben wir getan, oder?

**Comment by xyng** [comment]
Ups. Die Seite ist jedenfalls gebaut ^^

**Comment by kelzenberg** [comment]
nope, @Nilos hat die schon gebaut, nur deployed bitte
