### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by rugk** [whispeer/whispeerSite#4]
You have no license in your repo.
So I know you don't want to publish it under an  open-source license [1], but if you don't do it's essentially [this 'license'] (http://choosealicense.com/licenses/no-license/) which id described like this:
> You retain all rights and do not permit distribution, reproduction, or derivative works. You may grant some rights in cases where you publish your source code to a site that requires accepting terms of service. **For example, publishing code in a public repository on GitHub requires that you allow others to view and fork your code.**

So just you know that this code can still be forked.

[1] http://www.golem.de/news/whispeer-soziales-netzwerk-mit-ende-zu-ende-verschluesselung-1508-115671-2.html (German)

**Comment by Nilos** [comment]
That is fine with us.
