### ISSUE TITLE
Selecting Circles can be tricky

### ISSUE THREAD

**Issue by Soraltan** [whispeer/whispeerSite#5]
Hi,

this bug is somewhat related to the German version of the side, so I will use some German terms here. I named one of my circles 'Freunde' which is pretty close to the "default circle" 'Alle Freunde'. When I post something and want to select the circle 'Freunde' I can type 'Freund' but all I get as an option is 'Alle Freunde'. The only way I found to select the 'Freunde' circle is to add one circle after the other to the list of recipients until the circle 'Freunde' shows up, which is pretty annoying.

Maybe there is a similar issue with the English version of the side as well. Or it is a more general issue when there are two circle where one circle's name contains the full name of another circle?!?

Edit: Ok, I have new info on that matter: Apparently when I type "Freunde" there is strictly speaking more than just one option to select, namely two: "Alle Freunde" (first and the only one visible) and "Freunde" (second and not visible, but accessible by pushing the "down arrow" key). However if I select "Freunde" in that manner (pushing the down key), the entry remains invisible. I only know that "Freunde" was selected because when I press Enter it appears as the recipient of the post.

So it really seems to biol down to the matter that the dropdown-menu showing the circles which could be selected, is exactly large enough to show one entry, does not adapt its since according to the number of entries and cannot be scrolled.

System Info: Firefox 40.0.3 on Ubuntu Trusty (64bit).

Best Regards

**Comment by Nilos** [comment]
Somehow I was never watching the public repository (shame on me) and thus I only saw your issue now!
Working on it!

**Comment by Nilos** [comment]
This was fixed some time ago!
